config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:index, :new, :create, :show] do
    resources :bookmarks, only: [:create]
  end

  resources :bookmarks, only: [:destroy]

  root to: "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, :list_id, presence: true
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @bookmark = Bookmark.new(bookmark_params)

    @list = List.find(params[:list_id])
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = List.find(@bookmark.list_id)
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    puts 'test'
    puts @list
    @list.save
    redirect_to @list
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "components/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit ("Create") %>
<% end %>

app/views/lists/index.html.erb
<div class="container">

  <div class="home-banner">
    <h1>My Movies</h1>
  </div>

  <div class="cards-container">
    <div class="cards">
      <% @lists.each do |list| %>
        <%= link_to list_path(list) do %>
          <% if list.photo %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 600, crop: :fill %>">
              <h4><%= list.name %></h4>
            </div>
          <% else %>
            <%= "no photo found" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="new-list-container">
    <h3>Add a new list</h3>
    <%= render "form", list: @list %>
  </div>

</div>

app/views/lists/show.html.erb
<div class="container">

  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.photo.key, height: 600, crop: :fill %>')">
    <h1><%= @list.name %></h1>
  </div>

  <div class="movie-cards-container">
    <div class="movie-cards">
      <% @list.bookmarks.each do |bookmark| %>
        <div class="movie-card">
          <img src=<%= "https://image.tmdb.org/t/p/w500#{bookmark.movie.poster_url}" %> width="300" height="100"/>
          <div class="movie-card-info">
            <div class="title-rating">
              <h2><%= bookmark.movie.title %></h2>
              <p><%= bookmark.movie.rating %><i class="material-icons mr-1 inline-icon">star_outline</i></p>
            </div>
            <div>
              <p class="overview"><%= bookmark.movie.overview %></p>
            </div>
          </div>
          <div class="movie-card-footer">
            <div class="movie-card-comment">
              <p><i class="material-icons mr-1">format_quote</i><%= bookmark.comment %></p>
            </div>
            <div class="movie-card-delete">
              <%= link_to "Delete", bookmark_path(bookmark.id), class: "btn btn-ghost", method: :delete, data: { confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

    <div class="new_bookmark">
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.association :movie %>
          <%= f.input :comment %>
          <%= f.submit ("Add bookmark to list") %>
        <% end %>
    </div>

    <%= link_to "home", lists_path %>
</div>